Repository openedx/frontend-app-ora-grading, pull requests merged in 2024-12, with the labels that each got.

#325 fix: incorrect message for locking for Quince
  src/containers/ReviewModal/ReviewErrors/LockErrors.jsx
  src/containers/ReviewModal/ReviewErrors/LockErrors.test.jsx
Labels: bug, open-source-contribution, backport

#378 fix: incorrect message for locking
  src/containers/ReviewModal/ReviewErrors/LockErrors.jsx
  src/containers/ReviewModal/ReviewErrors/LockErrors.test.jsx
Labels: open-source-contribution, backport

#377 fix: incorrect message for locking
  src/containers/ReviewModal/ReviewErrors/LockErrors.jsx
  src/containers/ReviewModal/ReviewErrors/LockErrors.test.jsx
Labels: open-source-contribution, backport

#385 [Backport] fix: convert notification banner to text if accounts url is not set
  src/containers/NotificationsBanner/NotificationsBanner.test.jsx
  src/containers/NotificationsBanner/__snapshots__/NotificationsBanner.test.jsx.snap
  src/containers/NotificationsBanner/index.jsx
  src/containers/NotificationsBanner/messages.js
Labels: open-source-contribution

#323 fix: "An unexpected error occurred" for ORA response with corrupted attached file for Quince
  src/components/FilePreview/Banners/ErrorBanner.jsx
Labels: bug, open-source-contribution, backport

#358 fix: Fix for the Paragon modal shadow, which prevents clicking on an elements on the grading page
  src/containers/ReviewModal/ReviewModal.scss
Labels: open-source-contribution, backport

#376 fix: resolve react-pdf v7 worker configuration (fixes #330)
  package-lock.json
  package.json
  src/components/FilePreview/BaseRenderers/PDFRenderer.jsx
  src/components/FilePreview/BaseRenderers/pdfHooks.jsx
Labels: open-source-contribution

#366 chore: npm publish action removed
  .github/workflows/npm-publish.yml
  .releaserc
  package-lock.json
  package.json
Labels: open-source-contribution
